[project]
name = "OHW-py"
version = "0.1.0"
description = "Add a short description here"
authors = ["Alex Kerney <abk@mac.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "osx-64", "linux-aarch64"]

[tasks]
lab = "jupyter lab --port=8080 --ip=0.0.0.0"

[dependencies]
python = "3.12.*"
pangeo-notebook = "2024.08.07.*"
pixi-kernel = ">=0.4.0,<0.5"
pooch = ">=1.8.2,<1.9"
curl = ">=8.7.1,<8.8"
git = "*"
wget = ">=1.21.4,<1.22"
tar = ">=1.34,<2"
vim = ">=9.1.611,<9.2"
gh = "*"
nano = ">=8.1,<9"
gh-scoped-creds = ">=4.1,<5"
zarr = ">=2.18.2,<2.19"
netcdf4 = "*"
s3fs = "*"
ipykernel = "*"
flox = ">=0.9.8,<0.10"
opt_einsum = ">=3.3.0,<3.4"
numbagg = ">=0.8.1,<0.9"
fsspec = ">=2024.6.1"
gcsfs = ">=2024.6.1,<2024.7"
jupyterlab-git = ">=0.50.1,<0.51"

[feature.24-Callum.dependencies]
numpy = "*"
cartopy = "*"
pandas = "*"
gsw = "*"
matplotlib = "*"
seaborn = "*"
cmocean = "*"
cmcrameri = "*"
tqdm = "*"
argopy = "*"
ipyleaflet = "*"
searvey = "*"
shapely = "*"
cftime = "*"
ioos_qc = "*"
cf_xarray = "*"

[feature.24-Jiarui.dependencies]
pytorch = ">=2.3.1,<2.4"
torchvision = ">=0.18.1,<0.19"
einops = ">=0.8.0,<0.9"
matplotlib = ">=3.9.1,<3.10"
numpy = ">=2.0.1,<2.1"

[feature.24-Ciara.dependencies]
cfgrib = ">=0.9.14.0"
eccodes = ">=1.7.1"
ipykernel = ">=6.29.5"
numpy = ">=1.24.3"
matplotlib = ">=3.9.1"
pandas = ">=2.2.2"
xarray = ">=2024.1.0"
cartopy = ">=0.22.0"
boto3 = "*"
# botocore = ">=1.34.78"
requests = "*"
aiohttp = "*"

[feature.24-Rich.dependencies]
ipykernel = "*"
intake-xarray = "*"
fsspec = "*"
s3fs = "*"
xarray = "*"
cf_xarray = "*"
zarr = "*"
xoak = "*"
fastparquet = "*"
dask = "*"
coiled = "*"
dask-gateway = "*"
datashader = "*"
geoviews = "*"
hvplot = "*"
panel = "*"

[feature.24-Myranda.dependencies]
argopy = "*"
cartopy = "*"
matplotlib = "*"
pandas = "*"
scikit-learn = "*"
numpy = "*"


[environments]
default = {features = ["24-Callum", "24-Jiarui", "24-Ciara", "24-Rich", "24-Myranda"]}
