name: Build base Python image

on:
  push:
    branches:
      - main
    paths:
      - "py-base/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "py-base/**"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  shortsha:
    uses: ./.github/workflows/shortsha.yml

  build_push:
    needs: [shortsha]
    uses: ./.github/workflows/build-pixi-image.yml
    with:
      working_directory: ./py-base
      image_tag: ${{ needs.shortsha.outputs.shortsha }}
      image_name: python
      push_image: ${{ github.event_name == 'push' }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
